import { Inter } from "next/font/google";
import { JetBrains_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/components/design components/Header";
import PageTransition from "@/components/design components/PageTransition";

const inter = Inter({ subsets: ["latin"] });
const jetbrainsmono = JetBrains_Mono({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800"],
  variable: '--font-jetbrainsMono'
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={jetbrainsmono.variable}>
        <Header />

        <PageTransition>
          {children}
        </PageTransition>
      </body>
    </html>
  );
}
