import "./globals.css";
import Header from "@/components/design components/Header";
import PageTransition from "@/components/design components/PageTransition";

export const metadata = {
  title: "Auriol's Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`font-jetbrainsmono`}>
        <Header />

        <PageTransition>
          {children}
        </PageTransition>
      </body>
    </html>
  );
}
